[package]
name = "libnds_sys"
version = "0.1.0"
edition = "2021"
authors = ["SeleDreams"]
build = "build.rs"

[lib]
name = "libnds_sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[build-dependencies]
cc = "1.0.79"
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git",branch="main", features=["experimental"]}